---
dist: trusty

language: node_js
node_js:
  - "6.11"

sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - npm test
